### ISSUE TITLE
Not really REST?

### ISSUE THREAD

**Issue by guitarmanvt** [Mashape/unirest-python#8]
Hey, guys. I like that you've made the various HTTP verbs easy to program in Python.

However, I'm not seeing two main constraints that are required for something to be truly REST.

1. Resources - You've handled the underlying HTTP verbs, yes. But REST is all about Resources. And I don't see anything in this library that addresses Resources. (JSON is not really an application-specific resource type, despite popular opinion.)

2. HATEOAS - Unless they satisfy the Hypermedia constraint, web services are simply SOAP-like RPC (usually with JSON) over HTTP. Where does unirest handle hyperlinks in the Resources returned in the Response?

I appreciate the work you're doing to standardize the HTTP Verbs across languages. However, I'd really like to have full REST support.

**Comment by hutchic** [comment]
Hey @guitarmanvt this has been open for quite some time. If you had specific examples of what you'd change feel free to open a new issue or a PR. In my opinion the library as is will support all three levels of the REST maturity model including HATEOS. It's really up to the individual implementing the API to decide if they provide HATEOS not something the library enforces.
